traffic_flow:
    target: dev
    outputs:
        dev:
            type: postgres
            host: host.docker.internal
            user: airflow
            pass: airflow
            port: 5432
            dbname: dev
            schema: public
            threads: 4

    # target: superset
    # outputs:
    #     superset:
    #         type: mysql
    #         server: host.docker.internal
    #         username: superset
    #         password: superset
    #         port: 3306
    #         schema: superset
    #         ssl_disabled: True
