version: 2

models:
    - name: taxis
      description: "A dbt model for Taxi types"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: cars
      description: "A dbt model for Car types"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: buses
      description: "A dbt model for Bus types"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: Motorcycles
      description: "A dbt model for Motorcycle types"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: distribution
      description: "A dbt model for distribution of records across the data"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: heavy_vehicles
      description: "A dbt model for Heavy Vehicle types"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: medium_vehicles
      description: "A dbt model for Medium Vehicle types"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: least_avg_speed
      description: "A dbt model for least average speed recorded"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
